name: CI workflow

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install
        run: npm ci
      - name: Tests jest
        run: npm test
      - name: Tests e2e
        run: npm run test:e2e:ci
      - name: Upload screenshots when specs fail
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: ./cypress/screenshots
      - name: Upload videos when specs fail
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: videos
          path: ./cypress/videos
